runtime: go
api_version: go1

handlers:
- url: /components
  static_dir: components
  secure: always
- url: /bower_components
  static_dir: bower_components
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: _go_app
  secure: always
